import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { siteConfig } from "@/config/site";

export default function TermsPage() {
  return (
    <main className="flex-1 flex flex-col min-h-screen bg-background">
      <Header />

      {/* Content */}
      <div className="flex-1 max-w-2xl mx-auto w-full px-6 py-12">
        <h1 className="font-[family-name:var(--font-crimson)] text-3xl text-foreground mb-8">
          Terms of Service
        </h1>

        <div className="prose prose-stone dark:prose-invert">
          <p className="text-sm text-muted mb-8">
            Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}
          </p>

          <h2 className="font-[family-name:var(--font-crimson)] text-xl text-foreground mt-8 mb-4">
            Using {siteConfig.name}
          </h2>

          <p className="text-muted leading-relaxed mb-6">
            By using {siteConfig.name}, you agree to these terms. Please read
            them carefully.
          </p>

          <h2 className="font-[family-name:var(--font-crimson)] text-xl text-foreground mt-8 mb-4">
            Your content
          </h2>

          <p className="text-muted leading-relaxed mb-6">
            You own your reflection answers and the results generated from them.
            You grant us permission to use your answers solely to generate your
            result. You may share, download, and use your results however you wish.
          </p>

          <h2 className="font-[family-name:var(--font-crimson)] text-xl text-foreground mt-8 mb-4">
            AI-generated content
          </h2>

          <p className="text-muted leading-relaxed mb-6">
            Results are generated by AI based on your answers. While we strive
            for quality, we cannot guarantee that every result will be perfect or
            meaningful. The AI may occasionally produce unexpected results.
          </p>

          <h2 className="font-[family-name:var(--font-crimson)] text-xl text-foreground mt-8 mb-4">
            Acceptable use
          </h2>

          <p className="text-muted leading-relaxed mb-4">
            Please don&apos;t use {siteConfig.name} to:
          </p>

          <ul className="list-disc list-inside text-muted space-y-2 mb-6">
            <li>Generate harmful, abusive, or illegal content</li>
            <li>Attempt to extract or reverse-engineer our AI prompts</li>
            <li>Overload our systems with automated requests</li>
            <li>Impersonate others or misrepresent your identity</li>
          </ul>

          <h2 className="font-[family-name:var(--font-crimson)] text-xl text-foreground mt-8 mb-4">
            Changes to terms
          </h2>

          <p className="text-muted leading-relaxed mb-6">
            We may update these terms from time to time. Continued use of
            {siteConfig.name} after changes constitutes acceptance of the new
            terms.
          </p>

          <h2 className="font-[family-name:var(--font-crimson)] text-xl text-foreground mt-8 mb-4">
            Contact
          </h2>

          <p className="text-muted leading-relaxed">
            Questions? Email us at hello@innerverse.app
          </p>
        </div>
      </div>

      <Footer />
    </main>
  );
}
